### ISSUE TITLE
Sun getting huge.

### ISSUE THREAD

**Issue by ghost** [nanorover59/Starflight-Innovation#2]
![Screenshot 2024-08-22 122458](https://github.com/user-attachments/assets/50bc2a67-e14f-4619-a194-33e37b4119a3)

**Comment by nanorover59** [comment]
How did this happen? I know it is possible in currently released versions if you set time steps to zero, then save and load (that has been fixed for future versions). In general, it will happen in any scenario where the viewpoint vector for the sky renderer / solar system map is set to (0, 0, 0) at the center of the sun.

**Comment by nanorover59** [comment]
Closing this issue as it seems to be fixed with no occurrences in new versions the last few months.
